import test from 'node:test';
import assert from 'node:assert/strict';
import { verifyTransaction, sampleTransaction, rpc } from '../../demo/avalanche/avalanche.mjs';
const H='0x'+'a'.repeat(64), B='0x'+'b'.repeat(64), X='0x'+'c'.repeat(64), A='0x'+'1'.repeat(40), T='0x'+'2'.repeat(40);
function data(){return {eth_chainId:'0xa86a',eth_getTransactionByHash:{hash:H,blockHash:B,blockNumber:'0x20000000000001',from:A,to:T,value:'0xffffffffffffffffffffffffffff',nonce:'0x20000000000001'},eth_getTransactionReceipt:{transactionHash:H,blockHash:B,blockNumber:'0x20000000000001',from:A,to:T,status:'0x1'},eth_getBlockByNumber:{hash:B,number:'0x20000000000001',transactions:[H]},eth_blockNumber:'0x20000000000001'};}
function mock(d, calls=[]){return async (url,init)=>{const q=JSON.parse(init.body);calls.push({url,...q});return {ok:true,status:200,json:async()=>({jsonrpc:'2.0',id:q.id,result:d[q.method]})};};}
const run=d=>verifyTransaction({network:'mainnet',txHash:H,evidenceSource:'FIXTURE',fetchImpl:mock(d)});
for(const [network,chain] of [['mainnet','0xa86a'],['fuji','0xa869']])test(network+' chain and execution evidence',async()=>{const d=data();d.eth_chainId=chain;const calls=[];const r=await verifyTransaction({network,txHash:H,evidenceSource:'FIXTURE',fetchImpl:mock(d,calls)});assert.equal(r.assessment,'RECEIPT_SUCCESS_OBSERVED');assert.equal(r.business_state,'NOT_VERIFIED');assert.equal(r.evidence_source,'FIXTURE');assert.equal(calls[0].method,'eth_chainId');assert.equal(r.observed_fields.transaction.value,d.eth_getTransactionByHash.value);assert.equal(r.evidence_refs.length,4);});
for(const [label,change,want] of [
 ['chain mismatch',d=>d.eth_chainId='0x1','NETWORK_MISMATCH'],['invalid chain',d=>d.eth_chainId=null,'CHAIN_UNVERIFIED'],['null tx',d=>d.eth_getTransactionByHash=null,'TX_NOT_FOUND'],['null receipt',d=>d.eth_getTransactionReceipt=null,'RECEIPT_NOT_AVAILABLE'],['failed receipt',d=>d.eth_getTransactionReceipt.status='0x0','RECEIPT_FAILURE_OBSERVED'],['unknown status',d=>d.eth_getTransactionReceipt.status='0x2','UNSUPPORTED'],['missing block',d=>d.eth_getBlockByNumber=null,'CHAIN_UNVERIFIED'],
 ...['hash','blockHash','blockNumber','from','to'].map(k=>['tx '+k,d=>d.eth_getTransactionByHash[k]=k==='blockNumber'?'0x1':k==='from'||k==='to'?'0x'+'3'.repeat(40):X,'EVIDENCE_CONFLICT']),
 ...['transactionHash','blockHash','blockNumber','from','to'].map(k=>['receipt '+k,d=>d.eth_getTransactionReceipt[k]=k==='blockNumber'?'0x1':k==='from'||k==='to'?'0x'+'3'.repeat(40):X,'EVIDENCE_CONFLICT']),
 ['block hash',d=>d.eth_getBlockByNumber.hash=X,'EVIDENCE_CONFLICT'],['block number',d=>d.eth_getBlockByNumber.number='0x1','EVIDENCE_CONFLICT'],['missing receipt identity',d=>delete d.eth_getTransactionReceipt.transactionHash,'CHAIN_UNVERIFIED'],['missing block number',d=>delete d.eth_getTransactionReceipt.blockNumber,'CHAIN_UNVERIFIED'],['null target conflict',d=>d.eth_getTransactionByHash.to=null,'EVIDENCE_CONFLICT']
])test(label,async()=>{const d=data();change(d);const r=await run(d);assert.equal(r.assessment,want);assert.equal(r.business_state,'NOT_VERIFIED');});
test('contract creation null targets agree',async()=>{const d=data();d.eth_getTransactionByHash.to=null;d.eth_getTransactionReceipt.to=null;assert.equal((await run(d)).assessment,'RECEIPT_SUCCESS_OBSERVED');});
for(const [label,fetchImpl,reason] of [
 ['rpc error',async(_u,i)=>({ok:true,status:200,json:async()=>({jsonrpc:'2.0',id:JSON.parse(i.body).id,error:{code:-32000,message:'untrusted'}})}),'JSON_RPC_ERROR'],
 ['429',async()=>({ok:false,status:429}),'HTTP_429'],['5xx',async()=>({ok:false,status:503}),'HTTP_5XX'],['transport',async()=>{throw Error('untrusted secret');},'TRANSPORT_ERROR'],['timeout',async()=>new Promise(()=>{}),'TIMEOUT'],['body timeout',async()=>({ok:true,status:200,json:()=>new Promise(()=>{})}),'TIMEOUT'],['bad envelope',async()=>({ok:true,status:200,json:async()=>({jsonrpc:'2.0',id:999,result:'0xa86a'})}),'INVALID_RPC_ENVELOPE']
])test(label,async()=>{const r=await verifyTransaction({network:'mainnet',txHash:H,evidenceSource:'FIXTURE',fetchImpl,timeoutMs:10,retries:0});assert.equal(r.assessment,'RPC_UNAVAILABLE');assert.equal(r.reason_code,reason);assert.equal(r.business_state,'NOT_VERIFIED');assert.ok(!JSON.stringify(r).includes('untrusted'));});
test('bounded retry and fixed endpoint',async()=>{let n=0;const r=await verifyTransaction({network:'mainnet',txHash:H,evidenceSource:'FIXTURE',fetchImpl:async url=>{assert.equal(url,'https://api.avax.network/ext/bc/C/rpc');n++;return {ok:false,status:429};},retries:10});assert.equal(n,2);assert.equal(r.reason_code,'HTTP_429');});
test('invalid inputs make no call',async()=>{for(const input of [{network:'evil',txHash:H},{network:'mainnet',txHash:'https://evil'}]){const r=await verifyTransaction({...input,fetchImpl:()=>assert.fail()});assert.equal(r.assessment,'UNSUPPORTED');}});
test('sample bounded and verified',async()=>{const calls=[];const r=await sampleTransaction({network:'mainnet',evidenceSource:'FIXTURE',fetchImpl:mock(data(),calls)});assert.equal(r.assessment,'RECEIPT_SUCCESS_OBSERVED');assert.equal(r.tx_hash,H);assert.ok(calls.length<=16);assert.equal(calls[0].method,'eth_chainId');});
test('sample only five recent blocks',async()=>{const d=data();d.eth_getBlockByNumber={hash:B,number:'0x20000000000001',transactions:[]};const calls=[];const baseFetch=mock(d,calls);const fetchImpl=(url,init)=>{const q=JSON.parse(init.body);if(q.method==='eth_getBlockByNumber')d.eth_getBlockByNumber.number=q.params[0];return baseFetch(url,init);};const r=await sampleTransaction({evidenceSource:'FIXTURE',fetchImpl});assert.equal(r.assessment,'TX_NOT_FOUND');assert.equal(calls.filter(c=>c.method==='eth_getBlockByNumber').length,5);});
test('rpc call budget applies including retries',async()=>{const budget={remaining:1};let calls=0;await assert.rejects(rpc('mainnet','eth_chainId',[],{budget,fetchImpl:async()=>{calls++;return {ok:false,status:503};}}),e=>e.code==='CALL_BUDGET_EXHAUSTED');assert.equal(calls,1);});
test('RPC forbids redirects away from official endpoint',async()=>{const d=data();const underlying=mock(d);const fetchImpl=(url,init)=>{assert.equal(init.redirect,'error');return underlying(url,init);};assert.equal((await verifyTransaction({network:'mainnet',txHash:H,evidenceSource:'FIXTURE',fetchImpl})).assessment,'RECEIPT_SUCCESS_OBSERVED');});
for(const evidenceSource of ['NOT_RUN','BLOCKED','UNKNOWN'])test('non-observational origin '+evidenceSource+' makes no request',async()=>{for(const fn of [verifyTransaction,sampleTransaction]){const result=await fn({network:'mainnet',txHash:H,evidenceSource,fetchImpl:()=>assert.fail('must not call')});assert.equal(result.assessment,'CHAIN_UNVERIFIED');assert.equal(result.reason_code,'EVIDENCE_ORIGIN_NOT_OBSERVATIONAL');assert.equal(result.business_state,'NOT_VERIFIED');}});
test('sample rejects discovery outside requested recent block',async()=>{const d=data();d.eth_blockNumber='0x64';d.eth_getBlockByNumber.number='0x1';const r=await sampleTransaction({evidenceSource:'FIXTURE',fetchImpl:mock(d)});assert.equal(r.assessment,'EVIDENCE_CONFLICT');});
test('sample rejects missing discovery identity',async()=>{const d=data();delete d.eth_getBlockByNumber.hash;const r=await sampleTransaction({evidenceSource:'FIXTURE',fetchImpl:mock(d)});assert.equal(r.assessment,'CHAIN_UNVERIFIED');});
test('sample rejects verified transaction from another block',async()=>{const d=data();let blocks=0;const baseFetch=mock(d);const fetchImpl=async(url,init)=>{const q=JSON.parse(init.body);if(q.method==='eth_getBlockByNumber'&&blocks++===0)return {ok:true,status:200,json:async()=>({jsonrpc:'2.0',id:q.id,result:{hash:X,number:d.eth_blockNumber,transactions:[H]}})};return baseFetch(url,init);};const r=await sampleTransaction({evidenceSource:'FIXTURE',fetchImpl});assert.equal(r.assessment,'EVIDENCE_CONFLICT');});
for(const origin of ['LIVE','FIXTURE','SYNTHETIC'])test('unreachable origin '+origin,async()=>{for(const fn of [verifyTransaction,sampleTransaction]){const r=await fn({network:'mainnet',txHash:H,evidenceSource:origin,retries:0,fetchImpl:async()=>{throw Error('transport');}});assert.equal(r.assessment,'RPC_UNAVAILABLE');assert.equal(r.evidence_source,origin==='LIVE'?'BLOCKED':origin);}});
test('partial live observations preserved on RPC failure',async()=>{const d=data();const fetchImpl=async(url,init)=>{if(JSON.parse(init.body).method==='eth_getTransactionReceipt')throw Error('transport');return mock(d)(url,init);};const r=await verifyTransaction({network:'mainnet',txHash:H,fetchImpl,retries:0});assert.equal(r.evidence_source,'BLOCKED');assert.equal(r.observed_fields.chain_id,'0xa86a');assert.equal(r.observed_fields.transaction.hash,H);assert.ok(r.limitations.some(x=>x.includes('partial')));});
test('sample rejects verified transaction at different height',async()=>{const d=data();d.eth_blockNumber='0x20000000000002';let blocks=0;const baseFetch=mock(d);const fetchImpl=async(url,init)=>{const q=JSON.parse(init.body);if(q.method==='eth_getBlockByNumber'&&blocks++===0)return {ok:true,status:200,json:async()=>({jsonrpc:'2.0',id:q.id,result:{hash:B,number:d.eth_blockNumber,transactions:[H]}})};return baseFetch(url,init);};assert.equal((await sampleTransaction({evidenceSource:'FIXTURE',fetchImpl})).assessment,'EVIDENCE_CONFLICT');});
test('sample rejects malformed discovery number',async()=>{const d=data();delete d.eth_getBlockByNumber.number;assert.equal((await sampleTransaction({evidenceSource:'FIXTURE',fetchImpl:mock(d)})).assessment,'CHAIN_UNVERIFIED');});
test('documented CLI reports unreachable RPC as BLOCKED',async()=>{const {spawnSync}=await import('node:child_process');const modulePath=new URL('../../demo/avalanche/avalanche.mjs',import.meta.url);const {fileURLToPath}=await import('node:url');const script=`globalThis.fetch=async()=>{throw Error('offline')};process.argv=['node',${JSON.stringify(fileURLToPath(modulePath))},'verify','--network','mainnet','--tx',${JSON.stringify(H)}];await import(${JSON.stringify(modulePath.href)});`;const child=spawnSync(process.execPath,['--input-type=module','-e',script],{encoding:'utf8',timeout:5000});assert.equal(child.status,2);const r=JSON.parse(child.stdout);assert.equal(r.assessment,'RPC_UNAVAILABLE');assert.equal(r.evidence_source,'BLOCKED');});
