import test from 'node:test';
import assert from 'node:assert/strict';
import {probeMermail} from '../../skills/mermail-send-verifier/scripts/live-mermail.mjs';
const tool={name:'list_mailboxes',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true}};
function bridge(response={structuredContent:{items:[]}},status={runtimeStatus:'connected',tools:{list_mailboxes:tool},authStatus:'oAuth'}){
 const calls=[]; return {calls,close(){calls.push(['close'])},async request(method,args){calls.push([method,args]);if(method==='initialize')return {userAgent:'fixture'};if(method==='thread/start')return {thread:{id:'fixture-thread'}};if(method==='mcpServerStatus/list')return {data:[{name:'mermail',...status}]};if(method==='mcpServer/tool/call')return response;throw Error('unexpected method') }};
}
test('live empty mailbox read separately proves initialization catalog and read',async()=>{
 const b=bridge();const r=await probeMermail({createBridge:async()=>b});assert.equal(r.connection.initialize,'PASS');assert.equal(r.connection.catalog,'PASS');assert.equal(r.connection.list_mailboxes,'PASS');assert.equal(r.connection.mailbox_count,0);assert.equal(r.connection.selected_record,'BLOCKED');assert.equal(r.connection.reason_code,'no_mailboxes');assert.equal(r.claim.evidence_source,'BLOCKED');assert.deepEqual(r.evidence.records,[]);assert.ok(b.calls.every(([m])=>m!=='turn/start'));
 const call=b.calls.find(([m])=>m==='mcpServer/tool/call')[1];assert.equal(call.tool,'list_mailboxes');assert.deepEqual(call.arguments,{});
});
test('catalog alone never proves live mailbox read',async()=>{const b=bridge({isError:true,content:[{type:'text',text:'private error Bearer should-not-leak'}]});const r=await probeMermail({createBridge:async()=>b});assert.equal(r.connection.catalog,'PASS');assert.equal(r.connection.list_mailboxes,'BLOCKED');assert.equal(r.claim.evidence_source,'BLOCKED');assert.equal(JSON.stringify(r).includes('should-not-leak'),false);});
test('runtime must be connected before catalog can count as live discovery',async()=>{const b=bridge(undefined,{runtimeStatus:null,tools:{list_mailboxes:tool}});const r=await probeMermail({createBridge:async()=>b});assert.equal(r.connection.catalog,'BLOCKED');assert.equal(b.calls.some(([m])=>m==='mcpServer/tool/call'),false);});
test('mailbox metadata never selects customer mail automatically',async()=>{const b=bridge({structuredContent:{items:[{public_id:'private-id',name:'Personal',email:'customer@private.invalid'}]}});const r=await probeMermail({createBridge:async()=>b});assert.equal(r.connection.reason_code,'mailbox_selection_required');assert.equal(r.connection.mailbox_count,1);assert.equal(b.calls.filter(([m])=>m==='mcpServer/tool/call').length,1);assert.equal(JSON.stringify(r).includes('private.invalid'),false);assert.equal(JSON.stringify(r).includes('private-id'),false);});
test('unexpected response envelope fails closed instead of interpreting it as empty',async()=>{const b=bridge({structuredContent:{mailboxes:[]}});const r=await probeMermail({createBridge:async()=>b});assert.equal(r.connection.list_mailboxes,'BLOCKED');assert.equal(r.connection.reason_code,'unrecognized_mailbox_response');});
test('transport failure produces bounded safe evidence and closes bridge',async()=>{const b=bridge();b.request=async()=>{throw Error('secret failure')};const r=await probeMermail({createBridge:async()=>b});assert.equal(r.claim.evidence_source,'BLOCKED');assert.equal(r.evidence.error,'EVIDENCE_UNAVAILABLE');assert.equal(JSON.stringify(r).includes('secret failure'),false);assert.deepEqual(b.calls,[['close']]);});
