import {buildReport} from './build-report.mjs';
const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function display(value) { return value === null || value === undefined ? 'UNKNOWN' : typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value); }
function card(title, record, index) {
  const fields = [['Case',record.case_id],['Claim',record.claim_type],['Capture time',record.captured_at],['Observed evidence',record.observed_fields],['Evidence references',record.evidence_refs],['Limitations',record.limitations]];
  if (title === 'Mail Record') fields.splice(2,0,['Mailbox',record.mailbox_id],['Selected record',record.selected_email_id],['Expected recipient',record.expected_recipient],['Record status',record.record_status]);
  if (title === 'Avalanche Execution') fields.splice(2,0,['Network',record.network],['Transaction',record.tx_hash]);
  return `<section class="card"><div class="eyebrow">${index} / EVIDENCE LAYER</div><h2>${escape(title)}</h2><p class="source">SOURCE · ${escape(display(record.evidence_source))}</p><div class="assessment">${escape(display(record.assessment))}</div><dl>${fields.map(([key,value])=>`<dt>${escape(key)}</dt><dd><pre>${escape(display(value))}</pre></dd>`).join('')}</dl>${record.warning ? `<p class="warning">${escape(record.warning)}</p>` : ''}</section>`;
}
/** Reapply publication boundary even when caller supplies a hand-built report. */
export function renderReport(input) {
  const report = buildReport({mail:input.mail,chain:input.chain,mode:input.mode,capturedAt:input.captured_at});
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${escape(report.title)}</title><style>
:root{color-scheme:dark;--bg:#101925;--panel:#1a2838;--line:#3d5369;--text:#edf5fd;--muted:#b3c4d7;--accent:#86e1d7}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:17px/1.5 system-ui,sans-serif}main{max-width:1540px;margin:auto;padding:44px 36px}header{border-bottom:1px solid var(--line);padding-bottom:28px;margin-bottom:28px}.eyebrow{font-size:12px;letter-spacing:.17em;color:var(--accent);font-weight:700}h1{font-size:clamp(30px,4vw,54px);line-height:1.12;margin:14px 0}header p{color:var(--muted);margin:12px 0}.principle{font-size:24px;color:var(--text)}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.card{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:24px;min-width:0}h2{font-size:24px;min-height:72px;margin:14px 0}.source{font-size:13px;font-weight:700;color:var(--accent)}.assessment{padding:14px;background:#0d1d2a;border-left:4px solid var(--accent);overflow-wrap:anywhere;font-size:17px;font-weight:750}dt{font-size:12px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);margin-top:20px}dd{margin:5px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.5 ui-monospace,monospace;margin:0}.warning{border-top:1px solid var(--line);padding-top:20px;color:#ffe3a1;font-size:13px;font-weight:700}footer{margin-top:24px;color:var(--muted);font-size:14px}@media(max-width:1000px){.grid{grid-template-columns:1fr}h2{min-height:0}main{padding:24px 18px}}@media print{body{background:white;color:black}.grid{display:block}.card{break-inside:avoid;margin:14px 0;background:white;color:black}.assessment{background:#eee;color:black}}
</style></head><body><main><header><div class="eyebrow">COMPLETION CLAIM → OBSERVED EVIDENCE</div><h1>${escape(report.title)}</h1><p>${escape(report.subtitle)}</p><p class="principle">An agent saying ‘done’ is not evidence.</p><p>Mode: ${escape(report.mode)} · Report generated: ${escape(display(report.captured_at))}</p></header><div class="grid">${card('Mail Record',report.mail,'01')}${card('Avalanche Execution',report.chain,'02')}${card('Business / Payment Relationship',report.business,'03')}</div><footer>Draft is not sent. A sent record does not establish delivery or reading. Execution success does not establish a payment relationship.</footer></main></body></html>`;
}
